max_objects_per_scene: 10
max_question_tokens_per_scene: 50
question_vocabulary_size: 93
embedding_dim: 128
hidden_dim: 128
inter_dim: 256
num_token_types: 4
num_attention_heads: 8
num_bert_layers: 5
num_output_classes: 28
use_bidirectional_encoder: 1

num_colors: 8
num_shapes: 5
num_materials: 2
num_sizes: 2
num_positions: 3
num_scene_positions: 4
num_questions_per_image: 10


max_epochs: 5
batch_size: 64
lr: 0.00025
scheduler_step_size: 5
scheduler_gamma: 1.5
log_every: 100
validate_every: 2000
early_stopping: 3
save_every_epochs: 100

g_layers: [256,256,256,256]
question_injection_position: 0
f_fc1: 256
f_fc2: 256
rl_dropout: 0.2