model_architecture: DeltaSQFormerPreLNLinear

max_objects_per_scene: 10
max_question_tokens_per_scene: 50
question_vocabulary_size: 93
embedding_dim: 256
hidden_dim: 256
inter_dim: 512
num_token_types: 3
num_attention_heads: 8
num_bert_layers: 5
num_output_classes: 28
use_bidirectional_encoder: 1


num_colors: 8
num_shapes: 5
num_materials: 2
num_sizes: 2
num_positions: 3
num_scene_positions: 4
num_questions_per_image: 10
num_special_heads: 1

max_epochs: 170
batch_size: 64
lr: 0.00005
max_lr: 0.0005
max_batch_size: 512
scheduler_step_size: 10
bs_scheduler_step_size: 10
scheduler_gamma: 1.8
bs_scheduler_gamma: 2
log_every: 500
validate_every: 20000
early_stopping: 10


g_layers: [256,256,256,256]
question_injection_position: 0
f_fc1: 256
f_fc2: 256
rl_dropout: 0.2
n_workers: 0

attention_temperature: 1.0
use_mbe_pruning: False
mbe_pruning_base: 0.0
use_random_pruning: False
random_pruning_base: 0.95
use_att_entropy_loss: False
att_entropy_loss_base: 0.01